# Generated by Django 3.1.2 on 2020-10-05 00:51

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio_economic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family_head_name', models.CharField(max_length=100, verbose_name='Nombre del responsable de la falimia')),
                ('family_head_relationship', models.CharField(max_length=50, verbose_name='Relacion con el responsable de la familia')),
                ('house_type', models.CharField(max_length=100, verbose_name='tipo de vivienda')),
                ('house_condition', models.CharField(max_length=100, verbose_name='condicion de vivienda')),
                ('average_amount_received', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='monto promedio recibido')),
                ('use_dinning_hall', models.CharField(max_length=255, verbose_name='Usa el comedor, especifique el porque')),
                ('schedule', models.CharField(max_length=50, verbose_name='horario para usar el comedor')),
                ('transport', models.CharField(max_length=255, verbose_name='medio de trasporte, especifique')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('job_perform', models.CharField(max_length=100, verbose_name='Trabajo que desempeña')),
                ('work_address', models.TextField(verbose_name='Direccion')),
                ('work_phone', models.CharField(max_length=50, verbose_name='telefono')),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=50, verbose_name='Sueldo')),
            ],
            options={
                'verbose_name': 'Socio_economic',
                'verbose_name_plural': 'Socio_economics',
                'db_table': 'socio_economic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=100, verbose_name='Cedula')),
                ('sex', models.CharField(max_length=100, verbose_name='Sexo')),
                ('born_date', models.DateField(default=datetime.datetime(2020, 10, 5, 0, 51, 49, 270709, tzinfo=utc), verbose_name='Fecha de nacimiento')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad de nacimiento')),
                ('state', models.CharField(max_length=100, verbose_name='Estado de nacimiento')),
                ('civil_state', models.CharField(max_length=50, verbose_name='Estado civil')),
                ('home_address', models.TextField(verbose_name='Direccion de domicilio')),
                ('phone', models.CharField(max_length=50, verbose_name='telefono')),
                ('home_phone', models.CharField(max_length=50, verbose_name='telefono de casa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('live_with', models.CharField(max_length=255, verbose_name='Vives cob')),
                ('disability', models.CharField(max_length=100, verbose_name='Discapacidad que posee')),
                ('certificate_number', models.IntegerField(verbose_name='Numero de certificado de discapacidad')),
                ('disability_grade', models.CharField(max_length=100, verbose_name='Gravedad de la discapacidad')),
                ('tecnic_help', models.CharField(max_length=100, verbose_name='Tipo de ayuda tecnica')),
                ('medical_diagnostic', models.TextField(verbose_name='Diagnostico medico')),
                ('disability_causes', models.TextField(verbose_name='Causas de la discapacidad')),
                ('independent', models.BooleanField(default=True, verbose_name='Independencia en actividades cotidianas')),
                ('free_time_activities', models.TextField(blank=True, null=True, verbose_name='Actividades de tiempo libre')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de contacto')),
                ('contact_relationship', models.CharField(max_length=100, verbose_name='Parentesco de contacto')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='numero de contacto')),
                ('contact_address', models.TextField(verbose_name='Direccion de contacto')),
                ('contact_emergency_address', models.TextField(verbose_name='Direccion de traslado de emergencia')),
                ('surgical_treatment', models.TextField(verbose_name='Tratamiento quirurjico')),
                ('permanent_treatment', models.TextField(verbose_name='Tratamiento permanente')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uneg_assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(max_length=100, verbose_name='tipo de beneficio')),
                ('income_date', models.CharField(max_length=100, verbose_name='fecha de ingreso')),
                ('last_assigned_area', models.CharField(max_length=100, verbose_name='ultima area asignada')),
                ('last_supervisor', models.CharField(max_length=100, verbose_name='ultimo supervisor')),
                ('socio_economic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.socio_economic')),
            ],
            options={
                'verbose_name': 'Uneg_assistance',
                'verbose_name_plural': 'Uneg_assistances',
                'db_table': 'uneg_assistance',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='socio_economic',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.CreateModel(
            name='Financial_assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=100, verbose_name='Nombre de la institucion')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Monto mensual')),
                ('socio_economic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.socio_economic')),
            ],
            options={
                'verbose_name': 'Financial_assistance',
                'verbose_name_plural': 'Financial_assistances',
                'db_table': 'financial_assistance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Family_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('relationship', models.CharField(max_length=100, verbose_name='Relacion')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('institute_grade', models.CharField(max_length=100, verbose_name='Grado de institucion')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupacion u oficio')),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Ingreso familiar')),
                ('live_at_home', models.BooleanField(default=True, verbose_name='Vive en el hogar')),
                ('socio_economic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.socio_economic')),
            ],
            options={
                'verbose_name': 'Family_group',
                'verbose_name_plural': 'Family_groups',
                'db_table': 'family_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discapacity_relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100, verbose_name='Relacion')),
                ('consists', models.TextField(verbose_name='Consiste')),
                ('socio_economic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.socio_economic')),
            ],
            options={
                'verbose_name': 'Discapacity_relation',
                'verbose_name_plural': 'Discapacity_relations',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=100, verbose_name='Nombre de la institucion')),
                ('address', models.TextField(verbose_name='Direccion de la institucion')),
                ('city_state', models.CharField(max_length=100, verbose_name='Ciudad y estado')),
                ('graduation_year', models.CharField(max_length=4, verbose_name='Año de graduacion')),
                ('graduate_mention', models.CharField(max_length=100, verbose_name='Bachiller en')),
                ('institution_type', models.CharField(max_length=50, verbose_name='Tipo de institicion')),
                ('grade_point_average', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Promedio de notas')),
                ('uneg_headquarters', models.CharField(max_length=50, verbose_name='Nombre de la sede')),
                ('carrer_procject', models.CharField(max_length=50, verbose_name='Proyecto de carrera')),
                ('admission_date', models.DateField(default=datetime.datetime(2020, 10, 5, 0, 51, 49, 274614, tzinfo=utc), verbose_name='Fecha de admision')),
                ('entry_mode', models.CharField(max_length=100, verbose_name='Modalidad de ingreso')),
                ('academic_period', models.CharField(max_length=100, verbose_name='Periodo academico que cursa')),
                ('semester_level', models.IntegerField(verbose_name='Nivel de semestre')),
                ('academic_index', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Indice academico')),
                ('status', models.CharField(max_length=50, verbose_name='Estatus')),
                ('additional_resources', models.CharField(max_length=255, verbose_name='Recursos adicionales')),
                ('university_conditions', models.TextField(verbose_name='Condiciones de la universidad necesarias')),
                ('extracurricular_activities', models.TextField(verbose_name='Le gustaria participar en actividades extracurriculares')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Academic',
                'verbose_name_plural': 'Academics',
                'db_table': 'academic',
                'managed': True,
            },
        ),
    ]
